template header
ruleName
stakeLevel
salience
raiseThreshold
positionThreshold
minWinPercentage
requiresStrongEconomy
action

template "poker-rules"

rule "@{ruleName}"
activation-group "@{stakeLevel}"
salience @{salience}
when
    $r: Round()
    eval($r.getCurrentRaise() @{raiseThreshold} (min_bigger_raise * $r.getPot())
         && $r.getCurrentRaise() >= min_bigger_raise_blinds)
    @{(positionThreshold != null && positionThreshold.trim() != "") ? 
    "eval($r.getPlayerPosition() > " + positionThreshold + ")" : 
    ""}
    @{(minWinPercentage != null && minWinPercentage.trim() != "") ? 
        "eval(" + 
        (requiresStrongEconomy == "true" ? "($r.getStrongEconomy() || handService.getTableAggressiveness($r.getRoundNum()) > 0) && " : "") + 
        "handService.getWinPercentage($r.getHand()) >= " + minWinPercentage + ")" : ""}
then
    System.out.println("Action: @{action}");
end

end template
