
rule "HighStakesPremiumHand"
activation-group "high_stakes"
salience 10
when
    $r: Round()
    eval($r.getCurrentRaise() > (min_bigger_raise * $r.getPot()) && $r.getCurrentRaise() >= min_bigger_raise_blinds)
    

    
    
then
    System.out.println("Action: RAISE (High stake");
end

rule "HighStakesGoodPositionStrongHand"
activation-group "high_stakes"
salience 9
when
    $r: Round()
    eval($r.getCurrentRaise() > (min_bigger_raise * $r.getPot()) && $r.getCurrentRaise() >= min_bigger_raise_blinds)


    
    
then
    System.out.println("Action: RAISE (High stake");
end

rule "HighStakesGoodPositionMediumHandEconomy"
activation-group "high_stakes"
salience 8
when
    $r: Round()
    eval($r.getCurrentRaise() > (min_bigger_raise * $r.getPot()) && $r.getCurrentRaise() >= min_bigger_raise_blinds)



    
then
    System.out.println("Action: RAISE (High stake");
end

rule "HighStakesGoodPositionMediumHandAggTable"
activation-group "high_stakes"
salience 7
when
    $r: Round()
    eval($r.getCurrentRaise() > (min_bigger_raise * $r.getPot()) && $r.getCurrentRaise() >= min_bigger_raise_blinds)


    

then
    System.out.println("Action: RAISE (High stake");
end

rule "HighStakesBadPosition"
activation-group "high_stakes"
salience 6
when
    $r: Round()
    eval($r.getCurrentRaise() > (min_bigger_raise * $r.getPot()) && $r.getCurrentRaise() >= min_bigger_raise_blinds)
    


    
then
    System.out.println("Action: RAISE (High stake");
end

rule "HighStakesCallFallback"
activation-group "high_stakes"
salience -10
when
    $r: Round()
    eval($r.getCurrentRaise() > (min_bigger_raise * $r.getPot()) && $r.getCurrentRaise() >= min_bigger_raise_blinds)
    
    
    
    
then
    System.out.println("Action: CALL (High stakes fallback)");
end

rule "NormalStakesPremiumHand"
activation-group "normal_stakes"
salience 10
when
    $r: Round()
    eval($r.getCurrentRaise() <= (min_bigger_raise * $r.getPot()) && $r.getCurrentRaise() >= min_bigger_raise_blinds)
    

    
    
then
    System.out.println("Action: RAISE (Normal stake");
end

rule "NormalStakesGoodPositionEconomy"
activation-group "normal_stakes"
salience 9
when
    $r: Round()
    eval($r.getCurrentRaise() <= (min_bigger_raise * $r.getPot()) && $r.getCurrentRaise() >= min_bigger_raise_blinds)

    

    
then
    System.out.println("Action: RAISE (Normal stake");
end

rule "NormalStakesGoodPositionAggTablePlayable"
activation-group "normal_stakes"
salience 8
when
    $r: Round()
    eval($r.getCurrentRaise() <= (min_bigger_raise * $r.getPot()) && $r.getCurrentRaise() >= min_bigger_raise_blinds)


    

then
    System.out.println("Action: RAISE (Normal stake");
end

rule "NormalStakesGoodPositionMediumHand"
activation-group "normal_stakes"
salience 7
when
    $r: Round()
    eval($r.getCurrentRaise() <= (min_bigger_raise * $r.getPot()) && $r.getCurrentRaise() >= min_bigger_raise_blinds)


    
    
then
    System.out.println("Action: RAISE (Normal stake");
end

rule "NormalStakesBadPositionMediumHandEconomy"
activation-group "normal_stakes"
salience 6
when
    $r: Round()
    eval($r.getCurrentRaise() <= (min_bigger_raise * $r.getPot()) && $r.getCurrentRaise() >= min_bigger_raise_blinds)



    
then
    System.out.println("Action: RAISE (Normal stake");
end

rule "NormalStakesBadPositionStrongHand"
activation-group "normal_stakes"
salience 5
when
    $r: Round()
    eval($r.getCurrentRaise() <= (min_bigger_raise * $r.getPot()) && $r.getCurrentRaise() >= min_bigger_raise_blinds)


    
    
then
    System.out.println("Action: RAISE (Normal stake");
end

rule "NormalStakesCallFallback"
activation-group "normal_stakes"
salience -10
when
    $r: Round()
    eval($r.getCurrentRaise() <= (min_bigger_raise * $r.getPot()) && $r.getCurrentRaise() >= min_bigger_raise_blinds)
    
    
    
    
then
    System.out.println("Action: CALL (Normal stakes fallback)");
end


