package rules.fold

import com.ftn.sbnz.model.models.Round;
import com.ftn.sbnz.service.services.HandService;
import com.ftn.sbnz.service.services.HandEvalQueryService;

global HandEvalQueryService handEvalService;
global HandService handService;
global Double min_bigger_raise;
global Integer min_bigger_raise_blinds;
global Integer bad_position_treshold;


rule "Fold - Below Medium Hand"
activation-group "fold_decision"
salience 10
when
    $r: Round()
    eval(!handEvalService.isHandAtLeast($r.getHand(), "Playable"))
    
    
    
    
    
then
    $r.setSuggestedAction("FOLD");
    System.out.println("Backward: FOLD (Hand is below playable)");
end

rule "Fold - Big Raise vs Not Medium Hand"
activation-group "fold_decision"
salience 9
when
    $r: Round()
    
    eval(!handEvalService.isHandAtLeast($r.getHand(), "Medium"))
    
    eval($r.getCurrentRaise() > (min_bigger_raise * $r.getPot()) && $r.getCurrentRaise() >= min_bigger_raise_blinds)
    
    
then
    $r.setSuggestedAction("FOLD");
    System.out.println("Backward: FOLD (Big raise vs. not medium hand)");
end

rule "Fold - Bad Position vs Not Medium Hand"
activation-group "fold_decision"
salience 8
when
    $r: Round()
    
    eval(!handEvalService.isHandAtLeast($r.getHand(), "Medium"))
    eval($r.getPlayerPosition() <= bad_position_treshold)
    
    
    
then
    $r.setSuggestedAction("FOLD");
    System.out.println("Backward: FOLD (Bad position vs. not medium hand)");
end

rule "Fold - Below Medium Hand with Weakness"
activation-group "fold_decision"
salience 7
when
    $r: Round()
    
    eval(!handEvalService.isHandAtLeast($r.getHand(), "Medium"))
    
    
    eval($r.getStrongEconomy() == false)
    eval(!handService.isTableAggressive())
then
    $r.setSuggestedAction("FOLD");
    System.out.println("Backward: FOLD (Below medium hand with weak economy or low aggression)");
end

rule "Fold - Default No Fold"
activation-group "fold_decision"
salience -10
when
    $r: Round()
    
    
    
    
    
    
then
    $r.setSuggestedAction("NO FOLD");
    System.out.println("Backward: NO FOLD (No fold conditions met)");
end


