package rules.backward

import com.ftn.sbnz.model.models.Round;
import com.ftn.sbnz.service.services.HandService;

global HandService handService;
global Double min_bigger_raise;        // u % pota
global Integer min_bigger_raise_blinds;    // u blindovima
global Double risk_margin;             // za high stakes
global Integer bad_position_treshold;
global Double min_strong_hand;
global Double min_medium_hand;
global Double tableAggressiveness;     // ∑agresivnosti stola

// Glavni query: da li foldovati?
query shouldFold( Round r, String reason )
    weakHandFold( r, reason )
    or bigRaiseFold( r, reason )
    or badPositionFold( r, reason )
    or mediumEconomyFold( r, reason )
end


// Ako ruka slabija od min_weak_hand
query weakHandFold( Round r, String reason )
    belowMediumHand( r )
    reason := "Slaba ruka"
end


// Ako je raise velik a ruka nije dovoljno jaka
query bigRaiseFold( Round r, String reason )
    ( bigRaiseByBlinds( r ) or bigRaiseByPot( r ) )
    and weakHandForRaise( r, reason )
end


// // Ako smo u lošoj poziciji i ruka nije strong/medium
query badPositionFold( Round r, String reason )
    inBadPosition( r )
    and notStrongHand( r )
    and ( belowMediumHand( r ) or tableAggressionLow( r ) )
    reason := "Loša pozicija"
end


// Ako ruka slabija od medium + loša ekonomija/agresija
query mediumEconomyFold( Round r, String reason )
    belowMediumHand( r )
    and ( !hasStrongEconomy( r ) or tableAggressionLow( r ) )
    reason := "Slabija od medium + loša ekonomija/agresija"
end


// -----------------------------------------------------------------

// Veliki raise u odnosu na blindove
query bigRaiseByBlinds( Round r )
    $r : Round( $cr : currentRaise, $bb : bigBlindSize ) from r
    eval( $cr >= min_bigger_raise_blinds * $bb )
end


// Veliki raise u odnosu na pot
query bigRaiseByPot( Round r )
    $r : Round( $cr : currentRaise, $pot : pot ) from r
    eval( $cr > min_bigger_raise * $pot )
end


// Ruka nije dovoljno jaka
query weakHandForRaise( Round r, String reason )
    notStrongHand( r ) 
    and ( tableAggressionLow( r ) or belowMediumHand( r ) )
    reason := "Veliki raise - preslaba ruka"
end


// Ruka nije strong
query notStrongHand( Round r )
    $r : Round( $h : hand ) from r
    eval( handService.getWinPercentage($h) < min_strong_hand )
end


// Ruka manja od medium
query belowMediumHand( Round r )
    $r : Round( $h : hand ) from r
    eval( handService.getWinPercentage($h) < min_medium_hand )
end


// Agresija stola negativna
query tableAggressionLow( Round r )
    eval( tableAggressiveness < 0 )
end

// Igrač je u lošoj poziciji
query inBadPosition( Round r )
    $r : Round( $pos : playerPosition ) from r
    eval( $pos <= bad_position_treshold )
end


// Proverava da li igrač ima strong ekonomiju
query hasStrongEconomy( Round r )
    $r : Round( $eco : strongEconomy ) from r
    eval( $eco )
end